### ISSUE TITLE
MCrypt Fallback

### ISSUE THREAD

**Issue by fgarci03** [ezimuel/PHP-Secure-Session#16]
Although apparently this is incredibly rare, some servers may not have the MCrypt module installed/enabled.
It happened to me using CodeAnywhere.com Dev and SandBox. And also on Linux Mint, which apparently it's a known quirk. Weird thing was, on my website's server worked perfectly (I later found ou what happened).

I implemented on my own project a sort of fallback that warns the user that SecureSession will not be loaded, allowing the php code to run (mine gave me a blank page untill I found out the problem was with the module). So if the module is loaded, it's business as usual. If not, the code runs, but the user is warned that SecureSession.php not running, and can take appropriate action, without losing the website's functionality.

Do you think it's worth to workaround?

**Comment by ezimuel** [comment]
@fgarci03 I moved the check for `Mcrypt` extension in constructor (https://github.com/ezimuel/PHP-Secure-Session/blob/master/SecureSession.php#L86). Now, if you require the `SecureSession.php` and you don't have `Mcrypt` installed you will get an Exception.
Thanks for the feedback!
