### ISSUE TITLE
register_secure_session.php breaks application

### ISSUE THREAD

**Issue by HMAZonderland** [ezimuel/PHP-Secure-Session#23]
After installing this lib as an experimental dependency for my application it breaks it. This is due to the `chdir` & `require vendor/autoload.php`. Removing both lines fixes the problem.

**Comment by ezimuel** [comment]
@HMAZonderland Thanks for notice this! In my tests, I used a different autoloader but if you are going to use composer autoloader in your project it's already there. Fixed in master, sorry for that :(
