### ISSUE TITLE
UTF-8 serialize error for save in MongoDB

### ISSUE THREAD

**Issue by subversivo58** [ezimuel/PHP-Secure-Session#24]
I use a custom handler to save sessions in MongoDB.

I tried to adapt its handler to see if it came to an expected result: encrypt and save the database however, received a "Got invalid UTF-8 value serializing".

You have correction suggestions?

I know that support for saving in MongoDB is not part of his project but would like to serialize "UTF-8"?

I do not know the correct way to do this, I created a gist with the prototype.

[here found gist](https://gist.github.com/subversivo58/7ec04420a5b71c2017b0e0df8045b626)

Already grateful for any help.

**Comment by ezimuel** [comment]
@subversivo58 the encryption data produced by PHP-Secure-Session are in binary format. 
You can specify the usage of "UTF-8" in your application, for instance using `mb_internal_encoding("UTF-8");`. Let me know if this fixes the issue.

**Comment by subversivo58** [comment]
I tried mb_internal_encoding ("UTF-8") but failed. 

So I followed what his response suggested (code in UTF-8) and used utf8_encode () before saving in MongoDB [write function] and utf8_decode () to return the bank and before decrypt [read function].

This working fine now. Thanks!

![fine-works](https://cloud.githubusercontent.com/assets/6475273/18387364/9e54f74e-7672-11e6-809e-8b209dd229d5.PNG)

**Comment by subversivo58** [comment]
I have one more question I would like to incorporate part of its code to my already published on MIT License.

My code is a simple session handler to use MongoDB with this here on GitHub and Packagist.

If you allow me I would use for my handler has focus and MongoDB to be able to be retrieved session data in another language or even on another server.

It's possible?

[github source](https://github.com/subversivo58/mdbsh)
[packagist.org](https://packagist.org/packages/mdbsh/mdbsh)

**Comment by ezimuel** [comment]
@subversivo58 I'm glad that you solved. Regarding the source code you can do whatever you want. 
A link to this project will be nice to have in your documentation :)

**Comment by subversivo58** [comment]
Thank you very much.
