### ISSUE TITLE
How to know if it is working or not ?

### ISSUE THREAD

**Issue by the94air** [ezimuel/PHP-Secure-Session#25]
I have added PHP-Secure-Session as dependency in my project and i didn't notice any change in the session key. So how to know if it is working or not?

**Comment by kukoman** [comment]
Hiya, you can check the writing method https://github.com/ezimuel/PHP-Secure-Session/blob/master/src/SecureHandler.php#L74 and then the location where your sessions sits
In worst case (if your debugger isn't working), you can always user var_dump(...) to confirm

**Comment by ezimuel** [comment]
@the94air the session key will not change. You will see an additional COOKIE, named like `KEY_PHPSESSID`. 
Additional, you can check the content of the session data, and you will see encrypted value (unreadable). If you are using the default PHP session handler, that is file based. You can get the path of the session files using the [session_save_path()](http://php.net/manual/en/function.session-save-path.php) function.

**Comment by the94air** [comment]
yaa the session file name is `sess_s1hht0dlrpeoa0sp8g8ngnmg40` should it be like this?

**Comment by ezimuel** [comment]
@the94air yes, it sounds right. The second part of the name is a random value. If you open the file you will see binary data and not a PHP data structure.

**Comment by the94air** [comment]
Thanks guys for all the hard work, you are making our life easier. i have used your dependency in this [project](https://github.com/the94air/simplogin)
