### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by dcdeiv** [ezimuel/PHP-Secure-Session#26]
Can you please provide a full working demo?

- public page with a login form that set the session
- privates pages that check if the session is set else redirects to the public page to log in
- log out page

**Comment by ezimuel** [comment]
A demo for session encryption is already available [here](https://github.com/ezimuel/PHP-Secure-Session#demo). You are looking for a different project, there are many examples on the web for a login page with user authentication in PHP, for instance this [PHPAuth/PHPAuth](https://github.com/PHPAuth/PHPAuth) is the first that I found.
