### ISSUE TITLE
Cookie handling on first session start

### ISSUE THREAD

**Issue by gollumben** [ezimuel/PHP-Secure-Session#27]
Hi,

if I start the session for the first time from a fresh browser, the cookie for the key in getKey($name) does not exist and is not saved in my browser, since cookies are only written on page reload. If for whatever reason, I do a session_write_close() and the try to restart the session again, I get the implemented runtime exception. This makes sense: in the process of starting the session, an open command is executed. As the key cookie has not been set yet, SecureHandler creates a new key, which then leads to conflicts when decrypting already written data, since the new key and the previous one are different. In order to resolve this issue, I propose to change the function getKey to

```php
 protected function getKey($name)
    {
        if (empty($_COOKIE[$name])) {
            $key = random_bytes(64); // 32 for encryption and 32 for authentication
            $cookieParam = session_get_cookie_params();
            setcookie(
                $name,
                base64_encode($key),
                // if session cookie lifetime > 0 then add to current time
                // otherwise leave it as zero, honoring zero's special meaning
                // expire at browser close.
                ($cookieParam['lifetime'] > 0) ? time() + $cookieParam['lifetime'] : 0,
                $cookieParam['path'],
                $cookieParam['domain'],
                $cookieParam['secure'],
                $cookieParam['httponly']
            );
            $_COOKIE[$name] = base64_encode($key);
        } else {
            $key = base64_decode($_COOKIE[$name]);
        }
        return $key;
    }
```

i.e. setting the superglobal, $_COOKIE[$name], if created for the first time.

I changed this in my fork. I can create a pull request, if you agree.

Another question: Is it wise to store the decryption key in the cookies? I see that storing it in the session variables does not make any sense, but couldn't it be stored somewhere else?

Thank you for your help!
Ben

**Comment by hardyjohnson** [comment]
@gollumben At one point I was working on just this issue, not sure if this is helpful but I do have a PR to a local branch which may have some code which would help you. https://github.com/hardyjohnson/PHP-Secure-Session/pull/2/files

**Comment by ezimuel** [comment]
@gollumben ok, we need a unit test for this case. Can you provide one? Otherwise I can work on it. Let me know, thanks!

**Comment by gollumben** [comment]
Sorry for the late reply. Here is a minimal working example. It is important that you close your browser and open it again, since the cookies have to be deleted. You will see an error of the type

> Fatal error: Uncaught RuntimeException: Authentication failed in /var/www/html/securesession/vendor/ezimuel/php-secure-session/src/SecureHandler.php:125 Stack trace: #0 /var/www/html/securesession/vendor/ezimuel/php-secure-session/src/SecureHandler.php(63): PHPSecureSession\SecureHandler->decrypt('\xAF\xDD\xCD\xDF\x01A8$\xE1\x1A\xB8y\n\xD0~...', '\x86\x8A\xB0\xBC{\xB9u\x08\x88\x8F\xFD\xA8}\xCB\xEF...') #1 [internal function]: PHPSecureSession\SecureHandler->read('hpjckkp8cjfdoh6...') #2 /var/www/html/securesession/vendor/ezimuel/php-secure-session/test/demo/index.php(26): session_start() #3 {main} thrown in /var/www/html/securesession/vendor/ezimuel/php-secure-session/src/SecureHandler.php on line 125

If you reload, the error will be gone.

`<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

ini_set('session.save_handler', 'files');

$autoload = __DIR__ . '/../../../../../vendor/autoload.php';
if (! file_exists($autoload)) {
  echo "You need to execute <strong>composer install</strong>!";
  exit;
}
require_once $autoload;

// change the default session folder in a temporary dir
session_save_path(sys_get_temp_dir());
session_start();
session_write_close();

session_start();
session_write_close();

echo "End of file";
`

**Comment by ezimuel** [comment]
@gollumben We need to transform this in a unit test, I will work on it.

**Comment by ezimuel** [comment]
@gollumben I solved the issue providing a unit test with commit https://github.com/ezimuel/PHP-Secure-Session/commit/6ddb28c175a4747fcf9a68a439ce6aad5b1d0b95 /cc @hardyjohnson

**Comment by gollumben** [comment]
Cheers!
