### ISSUE TITLE
Please use specific exception

### ISSUE THREAD

**Issue by Danack** [ezimuel/PHP-Secure-Session#29]
Hi,

Currently the code here:

https://github.com/ezimuel/PHP-Secure-Session/blob/6ddb28c175a4747fcf9a68a439ce6aad5b1d0b95/src/SecureHandler.php#L125

Is throwing a \RuntimeException. It would allow more precise catching of exceptions if it threw an exception that had a specific meaning.

```
namespace PHPSecureSession;
class AuthenticationFailedException extends \RuntimeException {
}
```

as that would allow people to know they are only catching that type of exception, rather than RuntimeExceptions that could be coming from elsewhere in their code.

**Comment by ezimuel** [comment]
Fixed and released with [version 1.1.0](https://github.com/ezimuel/PHP-Secure-Session/releases/tag/v1.1.0).
