### ISSUE TITLE
Warning on autoload.php

### ISSUE THREAD

**Issue by eborguezao** [ezimuel/PHP-Secure-Session#35]
I installed the library with the command:
"composer require ezimuel / php-secure-session"

Then I include the "vendor / autoload.php" file in my .php file

I'm included autoload.php and returns:

You need to execute composer install!

In the directory of the file "composer.json", I executed the requested command, but nothing was increased or updated. The error persisted. I'm using Ampps in Windows environment with OpenSSL configured and SSL configured for localhost.

Help me, thanks.

**Comment by ezimuel** [comment]
Closing this issue since it's outdated. I'll open again if the error is still relevant.
